In [1]:
import numpy as np

### create an array of 4 elements
x1 = np.arange(4)
print("Array of 4 elements:", x1)
print("Notice the shape, this is rank 1 array:", x1.shape)
print("after transpose:", x1.T.shape)

Array of 4 elements: [0 1 2 3]
Notice the shape, this is rank 1 array: (4,)
after transpose: (4,)


In [2]:
### Data structures like Rank 1 arrays often cause ambiguous results, they do not behave as either row or column vectors consistently.
### for e.g transpose of such array outputs the same array
### so, its always recommended to explicitly specify the dimensions of an array

### USE 1: Rank1 array to row or column vector conversion

np.newaxis

In [3]:
### create a row vector by adding first dimension
print("row vector:", x1[np.newaxis, :] )
print(x1[np.newaxis, :].shape)

### create a column vector by adding second dimension
print("\n")
print("column vector:\n", x1[:, np.newaxis])
print(x1[:, np.newaxis].shape)

row vector: [[0 1 2 3]]
(1, 4)


column vector:
 [[0]
 [1]
 [2]
 [3]]
(4, 1)


np.reshape

In [4]:
print("Row vector using reshape:", x1.reshape((1, 4)))
print("column vector using reshape:\n", x1.reshape((4, 1)))

Row vector using reshape: [[0 1 2 3]]
column vector using reshape:
 [[0]
 [1]
 [2]
 [3]]


np.expand_dims: 

In [5]:
print("Row vector using expand_dims:",np.expand_dims(x1, axis=0)) 
print("column vector using expand_dims:\n", np.expand_dims(x1, axis=1))

Row vector using expand_dims: [[0 1 2 3]]
column vector using expand_dims:
 [[0]
 [1]
 [2]
 [3]]


### USE 2: Increase the dimension

In [57]:
x2 = np.arange(2*4*28).reshape(2,4,28)
x2.shape

(2, 4, 28)

Increasing the 3D to 5D

newaxis

In [7]:
### newaxis can not split a dimension, but insert new dimension like below
x2_3D_to_5D = x2[:, :, np.newaxis, np.newaxis, :]
print("Adding 2 more dimesnions to 3D vector to get 5D vector suing newaxis:", x2_3D_to_5D.shape)

Adding 2 more dimesnions to 3D vector to get 5D vector suing newaxis: (2, 4, 1, 1, 28)


Reshape

In [8]:
print("3D to 5D by adding 2 more dimensions using reshape:", x2.reshape(2,4,1,1,28).shape)
print("\nsplitting a dimension using reshape\n")
print("3D to 5D by splitting last dimension into3 using reshape:", x2.reshape(2,4,7,2,2).shape)

3D to 5D by adding 2 more dimensions using reshape: (2, 4, 1, 1, 28)

splitting a dimension using reshape

3D to 5D by splitting last dimension into3 using reshape: (2, 4, 7, 2, 2)


np.expand_dims

In [9]:
x2_4D = np.expand_dims(x2, axis=2)
print("expanding 3D to 5D by adding dimension to a specified axis:", np.expand_dims(x2_4D, axis=2).shape)

expanding 3D to 5D by adding dimension to a specified axis: (2, 4, 1, 1, 28)


### USE 2: Broadcasting

In [10]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([1,2,3])

x1+x2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [11]:
print("x1:", x1)
print("x1 shape:", x1.shape)

### In order to broadcast, we need to increase the dimension of one of them
x1_newdim = x1[:, np.newaxis]
print("x1 column vector:\n", x1_newdim)
print(x1_newdim.shape)

### Now, the two arrays can be added
x1_newdim+ x2

x1: [1 2 3 4 5]
x1 shape: (5,)
x1 column vector:
 [[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])